version: "3.9"

services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
      - 27017:27017



